version: '3'

services:
    cbdb:
        image: couchbase/server:5.0.0-beta2
        ports:
            - "8091-8094:8091-8094"
            - "11207-11210:11207-11210"
            - "18091-18094:18091-18094"
        volumes:
            - ~/couchbase/ns:/opt/couchbase/var
    nodejs:
        build:
          context: .
          dockerfile: Dockerfile-Node-App
